;;; Directory Local Variables
;;; See Info node `(emacs) Directory Variables' for more information.

;; WARNING!  DO NOT EDIT
;; generated by 'lein migae config' from etc/dir-locals.el.mustache
((clojure-mode
  (srcroot . "/Users/gar/dev/migae-examples/migae-tictactoe/src")
  (warroot . "/Users/gar/dev/migae-examples/migae-tictactoe/war")))

